Add liquidate margin test
morpho-org/morpho-blue pull request #598
Opened 2023-11-21 12:48 UTC by QGarchery

This PR tests the computation to make sure that a borrow position is safe (if nothing changes) for a period `elapsed`

2023-11-21 13:41 UTC, MerlinEgalite approved these changes
LGTM! Curious what was the motivation behind that test?

2023-11-21 13:52 UTC, QGarchery commented
> Curious what was the motivation behind that test?

This comes from the idea of @daejunpark in https://github.com/morpho-org/morpho-blue/pull/522, where we want to ensure that there is a computation to verify that, even with interest accrual, your borrow position will stay safe. This PR is more modest than testing all the possible functions after some time elapsed, but I think it captures most of the idea

2023-11-21 16:06 UTC, Rubilmax requested changes

2023-11-21 16:06 UTC, Rubilmax commented on test/forge/integration/LiquidateIntegrationTest.sol
> +        ).wDivDown(maxRatio);
There already exist a `_maxBorrow` util!

2023-11-22 09:06 UTC, Jean-Grimal submitted a review, later dismissed

2023-11-22 09:09 UTC, MathisGD submitted a review, later dismissed

2023-11-22 10:05 UTC, MathisGD commented on test/forge/integration/LiquidateIntegrationTest.sol
> +        ).wDivDown(maxRatio);
nice catch

https://github.com/morpho-org/morpho-blue/blob/f463e40f776acd0f26d0d380b51cfd02949c8c23/test/forge/BaseTest.sol#L366

2023-11-22 11:20 UTC, Rubilmax approved these changes

2023-11-23 09:19 UTC, Jean-Grimal approved these changes

2023-11-24 09:39 UTC, MathisGD approved these changes

2023-11-24 09:39 UTC, merged