fix(liquidation): fix repaid assets rounding
morpho-org/morpho-blue pull request #626
Opened 2023-12-05 08:56 UTC by Rubilmax

2023-12-05 08:57 UTC, Rubilmax commented
@adhusson wrote:

> Agree with rounding down seized assets since the `liquidate` parameters are controlled by the liquidator.
> 
> The test `testLiquidateSharesInputNoBadDebtRealized` is failing because the liquidator should now expect fewer assets seized.
> 
> Worth noting that the POC on cantina has a setup with 300 borrowed, 400 collateral. It runs for 399 iterations and consumes 11M gas before the the borrower runs out of collateral. Keeping the LTV constant, both the iterations and the gas necessary to empty the borrower's collateral go up linearly with the borrow[1](#user-content-fn-1-aca4120a11353c83735d49eaa00cd3de). For instance with 40k collateral at the start it takes 39999 iterations and 1.13B gas to steal all the collateral. You can't steal more than 1.15/price of collateral at a time (edit: added correct stealable amount).
> 
> ## Footnotes
> 1. using manual memory management to avoid quadratic memory costs [↩](#user-content-fnref-1-aca4120a11353c83735d49eaa00cd3de)

> > > You can't steal more than 1.15/price of collateral at a time
> > 
> > 
> > Can you explain how you get to that number pls?
> 
> Seized assets are `[ceil|floor](repaidSharesToAssets) * liquidationIncentiveFactor / collateralPrice` so you steal at most `MAX_LIQUIDATION_INCENTIVE_FACTOR/price`.

2023-12-05 09:20 UTC, Jean-Grimal submitted a review, later dismissed

2023-12-05 13:31 UTC, QGarchery requested changes

2023-12-05 13:31 UTC, QGarchery commented on test/forge/integration/LiquidateIntegrationTest.sol
> -    function testLiquidateMargin(LiquidateTestParams memory params, uint256 amountSeized, uint256 elapsed) public {
Why removing this test ? It should pass independently on the changes made on `liquidate`

2023-12-05 13:31 UTC, QGarchery commented on src/Morpho.sol
Given this new issue, I'm putting into question the importance to have the shares as input to the liquidate function. Removing this input is another (albeit radical) solution to this issue

2023-12-05 14:09 UTC, Rubilmax commented on src/Morpho.sol
Besides, it seems weird to remove the granularity of repaid shares to liquidate, because a liquidation is like a repay + withdraw collateral

2023-12-05 15:58 UTC, QGarchery commented on src/Morpho.sol
> Besides, it seems weird to remove the granularity of repaid shares to liquidate, because a liquidation is like a repay + withdraw collateral

By the same logic it should also expose a liquidate `repaidAssets` entrypoint. Ideally we would have a use case in mind to enable another entrypoint

> The only issue I have is that seizedAssets input converted into repaidShares can be greater than borrowShares thus overflow

I think it's even more general, and there are situations where the collateral seized would be less than the full collateral. Typically this is in LTV range [LLTV, 1/LIF]. The choice to have the repaid shares entrypoint was to facilitate full liquidations in those cases, and the choice was made against making bad debt realization more of a natural choice. I'm still not fully convinced by the argument in favor, and I also feel like now the code is less clear because of it

2023-12-07 10:15 UTC, Jean-Grimal approved these changes

2023-12-07 14:41 UTC, closed without merging